apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-archlinux-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.archlinux.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-archlinux-cronjob
              image: "{{ .Values.mirror.archlinux.image.repository }}:{{ .Values.mirror.archlinux.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.archlinux.update.activeDeadlineMinutes }}
              volumeMounts:
                - name: exclude-txt
                  mountPath: "/opt/exclude.txt"
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: exclude-txt
              configMap:
                name: {{ .Release.Name }}-archlinux-mirror-configmap

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-manjaro-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.manjaro.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-manjaro-cronjob
              image: "{{ .Values.mirror.manjaro.image.repository }}:{{ .Values.mirror.manjaro.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.manjaro.update.activeDeadlineMinutes }}
              volumeMounts:
                - name: exclude-txt
                  mountPath: "/opt/exclude.txt"
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: exclude-txt
              configMap:
                name: {{ .Release.Name }}-manjaro-mirror-configmap

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-ubuntu-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.ubuntu.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-ubuntu-cronjob
              image: "{{ .Values.mirror.ubuntu.image.repository }}:{{ .Values.mirror.ubuntu.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.manjaro.update.activeDeadlineMinutes }}
          restartPolicy: OnFailure

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-debian-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.debian.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-debian-cronjob
              image: "{{ .Values.mirror.debian.image.repository }}:{{ .Values.mirror.debian.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.manjaro.update.activeDeadlineMinutes }}
          restartPolicy: OnFailure


---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-raspbian-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.raspbian.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-raspbian-cronjob
              image: "{{ .Values.mirror.raspbian.image.repository }}:{{ .Values.mirror.raspbian.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.manjaro.update.activeDeadlineMinutes }}
          restartPolicy: OnFailure

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-gentoo-cronjob
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.mirror.gentoo.update.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-gentoo-cronjob
              image: "{{ .Values.mirror.gentoo.image.repository }}:{{ .Values.mirror.gentoo.image.tag | default .Chart.AppVersion }}"
              env:
                - name: SYNC_TIMEOUT_MIN
                  value: {{ .Values.mirror.manjaro.update.activeDeadlineMinutes }}
              volumeMounts:
                - name: exclude-txt
                  mountPath: "/opt/exclude.txt"
                  readOnly: true
          restartPolicy: OnFailure
          volumes:
            - name: exclude-txt
              configMap:
                name: {{ .Release.Name }}-gentoo-mirror-configmap

