apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-archlinux-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.archlinux.pv.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-manjaro-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 350Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.manjaro.pv.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ubuntu-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 450Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.ubuntu.pv.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-debian-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.debian.pv.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-raspbian-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.raspbian.pv.name }}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-gentoo-pvc
  labels:
    {{- include "linux-repository-mirror.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 850Gi
  selector:
    matchLabels:
      name: {{ .Values.mirror.gentoo.pv.name }}
