version: '3'

services:
  pacman:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/pacman-mirror:latest
    build:
      context: pacman
    volumes:
      - ./pacman/exclude.txt:/exclude.txt
      - /srv/mirror/pacman:/var/spool/pacman-mirror

  apt:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/apt-mirror:latest
    build:
      context: apt
    volumes:
      - /srv/mirror/apt:/var/spool/apt-mirror

  nginx:
    image: nginx:alpine

