version: '3'

services:
  pacman:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/archlinux-mirror:latest
    build:
      context: pacman
    volumes:
      - ./pacman/exclude.txt:/exclude.txt
      - /srv/mirror/archlinux:/var/spool/pacman-mirror

  apt-ubuntu:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/ubuntu-mirror:latest
    build:
      context: apt/ubuntu
    volumes:
      - /srv/mirror/ubuntu:/var/spool/apt-mirror/mirror

  apt-raspberrypi:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/raspberrypi-mirror:latest
    build:
      context: apt/raspberrypi
    volumes:
      - /srv/mirror/raspberrypi:/var/spool/apt-mirror/mirror

  nginx:
    image: nginx:alpine

