version: '3'

services:
  pacman:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/archlinux-mirror:latest
    build:
      context: pacman
    volumes:
      - ./pacman/exclude.txt:/exclude.txt
      - /srv/mirror/archlinux:/var/spool/pacman-mirror

  apt-ubuntu:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/ubuntu-mirror:latest
    build:
      context: apt/ubuntu
    volumes:
      - /srv/mirror/ubuntu:/var/spool/apt-mirror/mirror

  apt-debian:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/debian-mirror:latest
    build:
      context: apt/debian
    volumes:
      - /srv/mirror/debian:/var/spool/apt-mirror/mirror

  apt-raspberrypi:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/raspberrypi-mirror:latest
    build:
      context: apt/raspberrypi
    volumes:
      - /srv/mirror/raspberrypi:/var/spool/apt-mirror/mirror

  nginx:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
    build:
      context: nginx
    volumes:
      - /srv/mirror/ubuntu:/usr/share/nginx/apt/ubuntu:ro
      - /srv/mirror/debian:/usr/share/nginx/apt/debian:ro
      - /srv/mirror/raspberrypi:/usr/share/nginx/apt/raspberrypi:ro
      - /srv/mirror/archlinux:/usr/share/nginx/pacman:ro

