version: '3.8'

x-healthcheck: &default-healthcheck
  interval: "5s"
  timeout: "1s"
  retries: 3
  start_period: "20s"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

x-update-mirror: &update-mirror-template
  restart: on-failure:3
  stop_signal: SIGTERM
  logging: *default-logging
  environment:
    SYNC_TIMEOUT_MIN: 60

x-nginx: &nginx-template
  image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
  build:
    context: docker/nginx
  restart: always
  stop_signal: SIGTERM
  logging: *default-logging
  healthcheck:
    <<: *default-healthcheck
    test: curl -I http://localhost/ > /dev/null || exit 1
  labels:
    jp.ac.titech.e.ict.net.intra.mirror.description: "Linux package mirrors for laboratory local"

services:
  update-debian:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/debian-mirror:latest
    build:
      context: docker/apt
      args:
        context: debian
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/debian:/var/spool/apt-mirror/mirror/ftp.jp.debian.org/debian

  update-raspbian:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/raspbian-mirror:latest
    build:
      context: docker/apt
      args:
        context: raspbian
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/raspbian:/var/spool/apt-mirror/mirror/archive.raspbian.org/Linux/raspbian/raspbian

  update-ubuntu:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/ubuntu-mirror:latest
    build:
      context: docker/apt
      args:
        context: ubuntu
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/ubuntu:/var/spool/apt-mirror/mirror/jp.archive.ubuntu.com/ubuntu

  update-archlinux:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/archlinux-mirror:latest
    build:
      context: docker/pacman
      args:
        context: archlinux
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/archlinux:/var/spool/pacman-mirror

  update-manjaro:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/manjaro-mirror:latest
    build:
      context: docker/pacman
      args:
        context: manjaro
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/manjaro:/var/spool/manjaro-mirror

  update-gentoo:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/gentoo-mirror:latest
    build:
      context: docker/portage
      args:
        context: gentoo
    <<: *update-mirror-template
    volumes:
      - /srv/mirror/gentoo/gentoo-portage:/var/spool/portage-mirror/gentoo-portage
      - /srv/mirror/gentoo/gentoo:/var/spool/portage-mirror/gentoo

  nginx-all:
    <<: *nginx-template
    hostname: mirror.intra.net.ict.e.titech.ac.jp
    ports:
      - 10.0.5.11:80:80
    volumes:
      - /srv/mirror/ubuntu:/usr/share/nginx/apt/ubuntu:ro
      - /srv/mirror/debian:/usr/share/nginx/apt/debian:ro
      - /srv/mirror/raspberrypi:/usr/share/nginx/apt/raspberrypi:ro
      - /srv/mirror/archlinux:/usr/share/nginx/pacman/archlinux:ro
      - /srv/mirror/manjaro:/usr/share/nginx/pacman/manjaro:ro
      - /srv/mirror/gentoo:/usr/share/nginx/portage/gentoo:ro

  nginx-apt:
    <<: *nginx-template
    hostname: apt.mirror.intra.net.ict.e.titech.ac.jp
    ports:
      - 10.0.5.12:80:80
    volumes:
      - /srv/mirror/ubuntu:/usr/share/nginx/apt/ubuntu:ro
      - /srv/mirror/debian:/usr/share/nginx/apt/debian:ro
      - /srv/mirror/raspbian:/usr/share/nginx/apt/raspbian:ro

  nginx-pacman:
    <<: *nginx-template
    hostname: pacman.mirror.intra.net.ict.e.titech.ac.jp
    ports:
      - 10.0.5.13:80:80
    volumes:
      - /srv/mirror/archlinux:/usr/share/nginx/pacman/archlinux:ro
      - /srv/mirror/manjaro:/usr/share/nginx/pacman/manjaro:ro

  nginx-portage:
    <<: *nginx-template
    hostname: portage.mirror.intra.net.ict.e.titech.ac.jp
    ports:
      - 10.0.5.14:80:80
    volumes:
      - /srv/mirror/gentoo:/usr/share/nginx/portage/gentoo:ro
