version: '3'

services:
  apt-debian:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/debian-mirror:latest
    build:
      context: apt/debian
    volumes:
      - /srv/mirror/debian:/var/spool/apt-mirror/mirror/ftp.jp.debian.org/debian

  apt-raspbian:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/raspbian-mirror:latest
    build:
      context: apt/raspbian
    volumes:
      # - /srv/mirror/raspbian:/var/spool/apt-mirror/mirror/archive.raspbian.org/Linux/raspbian/raspbian
      - /srv/mirror/raspbian:/var/spool/apt-mirror/mirror

  apt-ubuntu:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/ubuntu-mirror:latest
    build:
      context: apt/ubuntu
    volumes:
      # - /srv/mirror/ubuntu:/var/spool/apt-mirror/mirror/jp.archive.ubuntu.com/ubuntu
      - /srv/mirror/ubuntu:/var/spool/apt-mirror/mirror

  pacman-arch:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/archlinux-mirror:latest
    build:
      context: pacman/archlinux
    volumes:
      - ./pacman/archlinux/exclude.txt:/exclude.txt
      - /srv/mirror/archlinux:/var/spool/pacman-mirror

  pacman-manjaro:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/manjaro-mirror:latest
    build:
      context: pacman/manjaro
    volumes:
      - ./pacman/manjaro/exclude.txt:/exclude.txt
      - /srv/mirror/manjaro:/var/spool/manjaro-mirror

  portage-gentoo:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/gentoo-mirror:latest
    build:
      context: portage/gentoo
    volumes:
      - ./portage/gentoo/exclude.txt:/exclude.txt
      - /srv/mirror/gentoo/gentoo-portage:/var/spool/portage-mirror/gentoo-portage
      - /srv/mirror/gentoo/gentoo:/var/spool/portage-mirror/gentoo

  nginx-all:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
    build:
      context: nginx
    ports:
      - 10.0.5.11:80:80
    volumes:
      - /srv/mirror/ubuntu:/usr/share/nginx/apt/ubuntu:ro
      - /srv/mirror/debian:/usr/share/nginx/apt/debian:ro
      - /srv/mirror/raspberrypi:/usr/share/nginx/apt/raspberrypi:ro
      - /srv/mirror/archlinux:/usr/share/nginx/pacman/archlinux:ro
      - /srv/mirror/manjaro:/usr/share/nginx/pacman/manjaro:ro
      - /srv/mirror/gentoo:/usr/share/nginx/portage/gentoo:ro

  nginx-apt:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
    build:
      context: nginx
    ports:
      - 10.0.5.12:80:80
    volumes:
      - /srv/mirror/ubuntu:/usr/share/nginx/apt/ubuntu:ro
      - /srv/mirror/debian:/usr/share/nginx/apt/debian:ro
      - /srv/mirror/raspbian:/usr/share/nginx/apt/raspbian:ro

  nginx-pacman:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
    build:
      context: nginx
    ports:
      - 10.0.5.13:80:80
    volumes:
      - /srv/mirror/archlinux:/usr/share/nginx/pacman/archlinux:ro
      - /srv/mirror/manjaro:/usr/share/nginx/pacman/manjaro:ro

  nginx-portage:
    image: docker.pkg.github.com/yamaoka-kitaguchi-lab/mirror-index-nginx:latest
    build:
      context: nginx
    ports:
      - 10.0.5.14:80:80
    volumes:
      - /srv/mirror/gentoo:/usr/share/nginx/portage/gentoo:ro
