nginx:
  image:
    repository: yamaoka-kitaguchi-lab/linux-repository-mirror/mirror-index-nginx
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60
  externalIPs:
    all: 10.0.5.11
    apt: 10.0.5.12
    pacman: 10.0.5.13
    portage: 10.0.5.14

mirror:
  archlinux:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/archlinux-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "*/20 * * * *"
      activeDeadlineMinutes: 60
    pv:
      name: archlinux-mirror-pv

  manjaro:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/manjaro-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "*/20 * * * *"
      activeDeadlineMinutes: 60
    pv:
      name: manjaro-mirror-pv

  ubuntu:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/ubuntu-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "*/20 * * * *"
      activeDeadlineMinutes: 60
    pv:
      name: ubuntu-mirror-pv

  debian:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/debian-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "*/20 * * * *"
      activeDeadlineMinutes: 60
    pv:
      name: debian-mirror-pv

  raspbian:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/raspbian-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "*/20 * * * *"
      activeDeadlineMinutes: 60
    pv:
      name: raspbian-mirror-pv

  gentoo:
    image:
      repository: yamaoka-kitaguchi-lab/linux-repository-mirror/gentoo-mirror
      tag: latest
      pullPolicy: IfNotPresent
    update:
      schedule: "0 0 * * *"
      activeDeadlineMinutes: 60
    pv:
      name: gentoo-mirror-pv
